name: "⚙️ PR Build"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  build:
    name: "⚙️ Build"
    uses: ./.github/workflows/build.yml
    with:
      upload_artifact: false
